/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as PosRouteImport } from "./routes/pos"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as AdminRouteImport } from "./routes/admin"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as PosIndexRouteImport } from "./routes/pos.index"
import { Route as AdminIndexRouteImport } from "./routes/admin.index"
import { Route as PosOrdersRouteImport } from "./routes/pos.orders"
import { Route as PosHistoryRouteImport } from "./routes/pos.history"
import { Route as AdminUsersRouteImport } from "./routes/admin.users"
import { Route as AdminReportsRouteImport } from "./routes/admin.reports"
import { Route as AdminProductsRouteImport } from "./routes/admin.products"
import { Route as AdminOrdersRouteImport } from "./routes/admin.orders"
import { Route as AdminInventoryRouteImport } from "./routes/admin.inventory"
import { Route as PosOrderIdRouteImport } from "./routes/pos.order.$id"

const PosRoute = PosRouteImport.update({
  id: "/pos",
  path: "/pos",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const PosIndexRoute = PosIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => PosRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AdminRoute,
} as any)
const PosOrdersRoute = PosOrdersRouteImport.update({
  id: "/orders",
  path: "/orders",
  getParentRoute: () => PosRoute,
} as any)
const PosHistoryRoute = PosHistoryRouteImport.update({
  id: "/history",
  path: "/history",
  getParentRoute: () => PosRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: "/users",
  path: "/users",
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: "/reports",
  path: "/reports",
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: "/products",
  path: "/products",
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: "/orders",
  path: "/orders",
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: "/inventory",
  path: "/inventory",
  getParentRoute: () => AdminRoute,
} as any)
const PosOrderIdRoute = PosOrderIdRouteImport.update({
  id: "/order/$id",
  path: "/order/$id",
  getParentRoute: () => PosRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/admin": typeof AdminRouteWithChildren
  "/login": typeof LoginRoute
  "/pos": typeof PosRouteWithChildren
  "/admin/inventory": typeof AdminInventoryRoute
  "/admin/orders": typeof AdminOrdersRoute
  "/admin/products": typeof AdminProductsRoute
  "/admin/reports": typeof AdminReportsRoute
  "/admin/users": typeof AdminUsersRoute
  "/pos/history": typeof PosHistoryRoute
  "/pos/orders": typeof PosOrdersRoute
  "/admin/": typeof AdminIndexRoute
  "/pos/": typeof PosIndexRoute
  "/pos/order/$id": typeof PosOrderIdRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/admin/inventory": typeof AdminInventoryRoute
  "/admin/orders": typeof AdminOrdersRoute
  "/admin/products": typeof AdminProductsRoute
  "/admin/reports": typeof AdminReportsRoute
  "/admin/users": typeof AdminUsersRoute
  "/pos/history": typeof PosHistoryRoute
  "/pos/orders": typeof PosOrdersRoute
  "/admin": typeof AdminIndexRoute
  "/pos": typeof PosIndexRoute
  "/pos/order/$id": typeof PosOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/admin": typeof AdminRouteWithChildren
  "/login": typeof LoginRoute
  "/pos": typeof PosRouteWithChildren
  "/admin/inventory": typeof AdminInventoryRoute
  "/admin/orders": typeof AdminOrdersRoute
  "/admin/products": typeof AdminProductsRoute
  "/admin/reports": typeof AdminReportsRoute
  "/admin/users": typeof AdminUsersRoute
  "/pos/history": typeof PosHistoryRoute
  "/pos/orders": typeof PosOrdersRoute
  "/admin/": typeof AdminIndexRoute
  "/pos/": typeof PosIndexRoute
  "/pos/order/$id": typeof PosOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/admin"
    | "/login"
    | "/pos"
    | "/admin/inventory"
    | "/admin/orders"
    | "/admin/products"
    | "/admin/reports"
    | "/admin/users"
    | "/pos/history"
    | "/pos/orders"
    | "/admin/"
    | "/pos/"
    | "/pos/order/$id"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/login"
    | "/admin/inventory"
    | "/admin/orders"
    | "/admin/products"
    | "/admin/reports"
    | "/admin/users"
    | "/pos/history"
    | "/pos/orders"
    | "/admin"
    | "/pos"
    | "/pos/order/$id"
  id:
    | "__root__"
    | "/"
    | "/admin"
    | "/login"
    | "/pos"
    | "/admin/inventory"
    | "/admin/orders"
    | "/admin/products"
    | "/admin/reports"
    | "/admin/users"
    | "/pos/history"
    | "/pos/orders"
    | "/admin/"
    | "/pos/"
    | "/pos/order/$id"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  PosRoute: typeof PosRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/pos": {
      id: "/pos"
      path: "/pos"
      fullPath: "/pos"
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin": {
      id: "/admin"
      path: "/admin"
      fullPath: "/admin"
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/pos/": {
      id: "/pos/"
      path: "/"
      fullPath: "/pos/"
      preLoaderRoute: typeof PosIndexRouteImport
      parentRoute: typeof PosRoute
    }
    "/admin/": {
      id: "/admin/"
      path: "/"
      fullPath: "/admin/"
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    "/pos/orders": {
      id: "/pos/orders"
      path: "/orders"
      fullPath: "/pos/orders"
      preLoaderRoute: typeof PosOrdersRouteImport
      parentRoute: typeof PosRoute
    }
    "/pos/history": {
      id: "/pos/history"
      path: "/history"
      fullPath: "/pos/history"
      preLoaderRoute: typeof PosHistoryRouteImport
      parentRoute: typeof PosRoute
    }
    "/admin/users": {
      id: "/admin/users"
      path: "/users"
      fullPath: "/admin/users"
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/reports": {
      id: "/admin/reports"
      path: "/reports"
      fullPath: "/admin/reports"
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/products": {
      id: "/admin/products"
      path: "/products"
      fullPath: "/admin/products"
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/orders": {
      id: "/admin/orders"
      path: "/orders"
      fullPath: "/admin/orders"
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/inventory": {
      id: "/admin/inventory"
      path: "/inventory"
      fullPath: "/admin/inventory"
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    "/pos/order/$id": {
      id: "/pos/order/$id"
      path: "/order/$id"
      fullPath: "/pos/order/$id"
      preLoaderRoute: typeof PosOrderIdRouteImport
      parentRoute: typeof PosRoute
    }
  }
}

interface AdminRouteChildren {
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminInventoryRoute: AdminInventoryRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PosRouteChildren {
  PosHistoryRoute: typeof PosHistoryRoute
  PosOrdersRoute: typeof PosOrdersRoute
  PosIndexRoute: typeof PosIndexRoute
  PosOrderIdRoute: typeof PosOrderIdRoute
}

const PosRouteChildren: PosRouteChildren = {
  PosHistoryRoute: PosHistoryRoute,
  PosOrdersRoute: PosOrdersRoute,
  PosIndexRoute: PosIndexRoute,
  PosOrderIdRoute: PosOrderIdRoute,
}

const PosRouteWithChildren = PosRoute._addFileChildren(PosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  PosRoute: PosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
